### PR TITLE
Support multiple primary keys in schema. Fixes #280

### LINKED ISSUE #280: Support multiple primary keys in schema
Here's a patch for that:

```
@@ -362,14 +362,21 @@ namespace SQLite
            if (!_tables.TryGetValue (ty.FullName, out map)) {
                map = GetMapping (ty, createFlags);
                _tables.Add (ty.FullName, map);
            }
            var query = "create table if not exists \"" + map.TableName + "\"(\n";
-           
-           var decls = map.Columns.Select (p => Orm.SqlDecl (p, StoreDateTimeAsTicks));
+
+      IEnumerable<TableMapping.Column> pks = from c in map.Columns where c.IsPK select c;
+      int numPKs = pks.Count();
+
+      var decls = map.Columns.Select(p => Orm.SqlDecl(p, StoreDateTimeAsTicks, numPKs == 1));
            var decl = string.Join (",\n", decls.ToArray ());
            query += decl;
+
+      if (numPKs > 1)
+        query += String.Format(",\nprimary key ({0})\n", string.Join(", ", pks.Select(c => "\"" + c.Name + "\"")));
+
            query += ")";

            var count = Execute (query);

            if (count == 0) { //Possible bug: This always seems to return 0?
@@ -1838,15 +1845,15 @@ namespace SQLite
    {
         public const int DefaultMaxStringLength = 140;
         public const string ImplicitPkName = "Id";
         public const string ImplicitIndexSuffix = "Id";

-       public static string SqlDecl (TableMapping.Column p, bool storeDateTimeAsTicks)
+       public static string SqlDecl (TableMapping.Column p, bool storeDateTimeAsTicks, bool setPK = true)
        {
            string decl = "\"" + p.Name + "\" " + SqlType (p, storeDateTimeAsTicks) + " ";

-           if (p.IsPK) {
+           if (setPK && p.IsPK) {
                decl += "primary key ";
            }
            if (p.IsAutoInc) {
                decl += "autoincrement ";
            }
```

### PR DESCRIPTION
**Pull request by mfeingol**

### CODE REVIEW

**Comment by mfeingol** [comment]
I will resubmit a version of this against latest.

**Comment by pkl728** [comment]
At some point it seems like you guys had multiple primary key support and then someone pulled it out.  Any chance to get this put back in?  I can create a pull request if required although it should be pretty similar to what was proposed here:  https://github.com/oysteinkrog/SQLite.Net-PCL/pull/160

**Comment by softlion** [comment]
Yup, also have my own imp here https://github.com/softlion/SQLite.Net-PCL

**Comment by praeclarum** [comment]
At first I was against composite PKs, but after reviewing the changes needed - I guess we could do them.

**Pull request closed without merging**
