### PR TITLE
Use icon because PackageIconUrl is deprecated

### PR DESCRIPTION
**Pull request by lindexi**
See [NuGet Error NU5030 | Microsoft Docs](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5030 )

### CODE REVIEW

**Review by XavierAP — APPROVED** [review]
Without this fix, every auto build fails.

**Comment by lindexi** [comment]
@XavierAP Thank you

**Comment by praeclarum** [comment]
Thank you so much. Unfortunately I accepted a PR that had this same change in it. I really appreciate your effort though.

**Comment by lindexi** [comment]
@praeclarum Never mind.

**Pull request closed without merging**
