### PR TITLE
Added Uri and UriBuilder types support

### PR DESCRIPTION
**Pull request by xperiandri**
Also updated NUnit version dependency to 2.6

### CODE REVIEW

**Comment by praeclarum** [comment]
You rewrote all the files. I will take this if you sync back up with master and send minimal changes. Thank you!

**Comment by xperiandri** [comment]
Do you mean tabs replaced by spaces within some of the files?

**Comment by kroggen** [comment]
Any news on this? Is URI already supported? If no, @xperiandri Can you send the minimal changes required for this to work? Do not change other lines, please. No tab/space changes.

**Comment by praeclarum** [comment]
Yes, sorry there are just too many edits here for the change.

Thank you very much for contributing, but I cannot accept it. When doing PRs, it's best to send small focused changes instead of large bulk ones.

If you would like, start over with a fresh rebasing from origin/master. And then apply your changes - just the ones concerning URIs. This should be done in a branch of your forked repo so that it doesn't affect your master branch. Once you have a simple diff, you can submit a new PR.

Since it has been a long time, please close this PR if you are no longer interested in doing this.

**Comment by xperiandri** [comment]
OK, created 2 new simple pull requests

**Pull request closed without merging**
