### PR TITLE
Support SQLitePCLRaw 2.0

### PR DESCRIPTION
**Pull request by iodes**
- Update to .NET Standard 2.0
- Support SQLitePCLRaw 2.0
- Support SQLCipher 4

### CODE REVIEW

**Comment by ericsink** [comment]
This is roughly what I planned to do for ericsink/SQLitePCL.raw#281 but I hadn't gotten around to doing it yet.

**Comment by candidodmv** [comment]
@ericsink any news about this update?

**Comment by ericsink** [comment]
I’m not a maintainer for SQLite-net. I was just saying that this PR is similar to one I intended to create.

**Comment by candidodmv** [comment]
@ericsink please to candidate to become a maintenner of this project I think that @praeclarum give up

**Comment by ericsink** [comment]
A few remarks on the @candidodmv suggestion that I become a maintainer here.

(1)  There are limits to how effective I can be as a maintainer of this library since I don't use it.  For example, I don't see myself working through the backlog of PRs containing new features and such.  I'd be constantly worried that I was introducing regressions.

(2)  That said, I do have some willingness to help with things like packaging and SQLitePCLRaw integration, if and only if @praeclarum wants that help.

(3)  I rather doubt @praeclarum would agree that he has given up.  He tends to wander away from this project every now and then, but he always comes back.  :-)

**Comment by candidodmv** [comment]
> A few remarks on the @candidodmv suggestion that I become a maintainer here.
> 
> (1) There are limits to how effective I can be as a maintainer of this library since I don't use it. For example, I don't see myself working through the backlog of PRs containing new features and such. I'd be constantly worried that I was introducing regressions.
> 
> (2) That said, I do have some willingness to help with things like packaging and SQLitePCLRaw integration, if and only if @praeclarum wants that help.
> 
> (3) I rather doubt @praeclarum would agree that he has given up. He tends to wander away from this project every now and then, but he always comes back. :-)

Thansk by feedback @ericsink about your thoughts related my suggestion. Looking from your view, it's doesn't apper to be a good idea and I'm also hopefully that @praeclarum came back as soon as possible, because many other libraries depends of this, otherwise will break the big engine.

**Comment by praeclarum** [comment]
Hi @iodes, thanks a lot for the effort!

You made a bunch of changes to the nuspec that I don't want so I'm going to close this PR.

**Pull request closed without merging**
