### PR TITLE
Solution for issue 881

### PR DESCRIPTION
**Pull request by csm101**
Hi, I added a test case for issue [881](https://github.com/praeclarum/sqlite-net/issues/881): if you add it to your clean master you can see it happening. The test case is in file tests/AsyncConcurrencyTestWithThreads.cs

 I refactored a lot of code by using async-aware Nito.AsyncEx 5.0 locking library: all task synchronization now uses AsyncLock class.

Around AsyncLock I built a g
Fixes #eneric class ObjectWithLock<T> that wraps an instance of type T and makes it available only if you obtain the lock. The source of this class is at the end of SqliteAsync.cs
it is used this way:

    var example = ObjectWithLock<MyClass>();
    using (var instanceAccess = example.Lock())
    {
        // instanceAccess is an IDisposable interface that exposes (through the Obj property) 
        // the lock-protected MyClass instance.
        // when the interface is disposed, the lock is released.
        instanceAccess.Obj.MyClassMethod()
    }

The above class supports also LockAsync() and timeouts for obtaining the resource

I Used such class for refactoring all the lock() protected objects in sqlite, for example now there are these two classes:

    internal class Mappings : ObjectWithLock<Dictionary<string, TableMapping>> 
    { }
    // i am indenting the code this whay only here, just to make the nested structure 
    // more understandable
    internal class InsertCommandMap :
          ObjectWithLock< 
                      Dictionary<
                                Tuple<string, string>, 
                                 ObjectWithLock<PreparedSqlLiteInsertCommand>
                          >
            > 
    { }
` 
I refactored the _TransactionDepth from a simple integer to a dedicated TransactionDephtTracker that holds that integer and protects it with an AsyncLock. The way I implemented it should solve also the "mild race condition" that was referred in the comments... or if I interpreted correctly which was the race condition the comment was referring to.

 I could be wrong but I felt It was a bit of an overkill to use InterlockedExchange (and methods like those) for achieving thread safety: I don't think that the speed improvement achieved by using InterlockedExchange instead of lock() is noticeable considering that immediately after you are going to have sqlite parse and execute things like "begin transaction" that surely involve disk access.  I feel that it is cleaner this way.

SQLiteConnectionWithLock now isn't anymore a class derived from SQLiteConnection, but it derives from ObjectWithLock<SQLiteConnection>. It bypasses the locking mechanism, by exposing them directly, only those properties and methods of SqliteConnection that do not require any locking, but to call methods that require exclusive access you need to obtain the embedded SqliteConnection instance by explicitly calling Lock(), LockAsync() (or the versions of these methods that accept a timeout parameter).

 As an optional feature (that I couldn't expose directly as a property of SqliteAsyncConnection because I think you added some trick in github that doesn't allow me to modify the external interface of such class) I added the possibility to use automatically the "BusyTimeout" set for the database also as a default timeout for SQLiteConnectionWithLock.Lock() calls anyway it is off by default and Lock() calls do wait forever. I added a test case for demonstrating this feature, anyway: (can still be enabled, but requires a bit more complicated call)

 I also modified a bit the implementation of the AsyncTests in order to allow them to be executed in parallel (I use NCrunch as a test runner, and It can do it) by having each test create its uniquely-named database file, instead of using a fixed filename used in turn by each test.

### CODE REVIEW

**Comment by praeclarum** [comment]
Hello,

Thank you very much for this work. However, I do not like the dependency on Nito. Surely this can be done with the BCL primitives.

Way too much has changed here for me to audit. That said, I totally want your unit tests so will take those bits.

Thank you!

**Comment by csm101** [comment]
Would you consider giving my changes a second tougth If i drop Nito.AsincEx and use the Monitor class as a locking mechanism? I think it is an easy change to be implemented.. and I feel that my changes make the code a bit more robust (see the racing conditions I eliminated) and make it more difficult to do introduce errors, since (the way I wrote it) it is impossible to access lock-protected data structures without using the "using (access=Resource.Lock()) {}" pattern...

**Comment by csm101** [comment]
(we can discuss the changes on a teamviewer session if you want, if you don't mind my bad spoken english)

**Comment by csm101** [comment]
I did remove the NitoAsync package and I rewrote the lockings using just the monitor Monitor class.
Are the merge conflicts I am seeing now due to something you have done to try to address the same bug?
 I am asking because my solution passes all the tests, I have fixed them to be run in parallel with each (avoiding conficting database file names among different tests) and they are have been running continuosly and in parallel (using NCrunch "churn mode") for 2 hours without having any issue..

**Comment by csm101** [comment]
Ah, ok... i didn't notice you already released a bugfix,

**Pull request closed without merging**
