### PR TITLE
Feature/284 guidsasblobs

### PR DESCRIPTION
**Pull request by gentledepp**
- [x] SQLiteConnectionString can be used to specify, that guids should be stored as blobs (16 bytes) instead of a varchar(36)
  🚀 Improves query performance
  🚀 Reduces required disk space
  🚀 Ensures compatibility with Microsoft.Data.SQLite and all derived projects (EF Core)
- [x] Fully backward compatible - ensured the SQLiteConnection constructors are not modified
- [x] Added tests for querying, storing, async and sync

We actually use this code in production in our iOS, Android, UWP app since 2 years now. 
So why not merge? 🤩

### CODE REVIEW

**Comment by gentledepp** [comment]
The build fails because your build script seems to be broken - I guess?

> Time Elapsed 00:00:01.54
> mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe tests/bin/Release/SQLite.Tests.dll --labels=On --trace=Info
> Cannot open assembly 'packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe': No such file or directory.
> make: *** [test] Error 2

**Comment by Panda-Sharp** [comment]
@praeclarum any feedback on this? I was looking into Guid as blob support, and this can be really useful!

**Comment by sshuzaFulcrum** [comment]
@praeclarum any chance this will ever get merged back, one of the databases I am working on uses BLOBs to store GUIDs, so having this would make reading the GUIDs valid for that column, right now I have to manually parse that entire table into the object representation because of the BLOBs.

**Comment by gentledepp** [comment]
@sshuzaFulcrum this most certainly never will, and unfortunately there is a good reason for this. Blobs in sqlite are not binary compatible across all devices.
For this reason, Microsoft.Data.Sqlite dropped the support for this as well, and they are now always treating GUIDs as text.

I myself will have to migrate our apps to use "guids as text" as well :-|

**Pull request closed without merging**
