### PR TITLE
update to SQLitePCLRaw 1.0

### PR DESCRIPTION
**Pull request by ericsink**
Update sqlite-net-pcl.nuspec with the new package ID for SQLitePCLRaw.bundle_green.

I have not built and test sqlite-net-pcl with this change.

### CODE REVIEW

**Comment by ps30** [comment]
@praeclarum possible to get this merged soon?

**Comment by ericsink** [comment]
More info on this PR:

Right now, the sqlite-net-pcl package dep is configured to bundle_green.  This means that sqlite-net-pcl users don't have to do anything if they are adding sqlite-net-pcl to an actual app project.

But if they are referencing sqlite-net-pcl from another PCL, they still have to add bundle_green to their app project.

Another option would be change the dep from bundle_green to just SQLitePCLRaw.core, and remove the call to SQLitePCL.Batteries.Init().

The downside is now ALL sqlite-net-pcl users need to (1) add a SQLitePCLRaw bundle to their app project(s), and (2) call SQLitePCL.Batteries.Init().  If they don't, an exception will be thrown at runtime.

But the upside is that now they can choose a different bundle if they want.  Like, for example, bundle_sqlcipher.

This is a tradeoff, the result of which could be expressed in terms of which users will be annoyed and how.  :-)

The "dep on just .core" path triggers users asking "Why do I get this exception thrown when I call SQLite stuff?"  The answer to this one is "Add SQLitePCLRaw.bundle_whatever to your app project and call SQLitePCL.Batteries.Init()"

The "dep on bundle_green" path triggers users asking "How do I use sqlite-net-pcl with sqlcipher?"  Or "How do I use sqlite-net-pcl with a custom SQLite build?"  The answer to these questions is "You basically can't."

**Comment by ericsink** [comment]
More docs on this matter at hand:

https://github.com/ericsink/SQLitePCL.raw/wiki/SQLitePCL.Batteries.Init

**Comment by praeclarum** [comment]
Woo hoo!

**Pull request merged**
