### PR TITLE
Read queries no longer use the connection pool

### PR DESCRIPTION
**Pull request by Clancey**

### CODE REVIEW

**Comment by praeclarum** [comment]
But is it safe? If you're willing to watch for Issues - I'll take this :-)

**Comment by Clancey** [comment]
According to the docs yes. Serialized is the default mode. I have a snippet that can force serialized mode! https://www.sqlite.org/threadsafe.html

**Comment by Clancey** [comment]
static SQLiteAsyncConnection ()
		{
			//This will globally set the state to Serialized
			SQLite3.Shutdown ();
			SQLite3.Config (SQLite3.ConfigOption.Serialized);
			SQLite3.Initialize ();
		}

**Comment by ericsink** [comment]
How much testing has this seen against recent sqlite-net-pcl builds?  Some of the related code has seen change over the last few months.  For example, SQLite3.Config didn't work until (some recent version I can't remember) because of an issue with SQLitePCL.raw.

Also, FWIW, serialized is the default mode, but not (IIRC) for the system sqlite built in to iOS, which by default is what sqlite-net-pcl uses, because it takes its dep on bundle_green.

I'm not opposing this PR.  I'm just trying to add a little info which might be relevant.  :-)

**Comment by Clancey** [comment]
I have been using this in the non-pcl version for years in live apps.  I am just now migrating to the PCL version.

**Comment by Clancey** [comment]
Lets close this pull request. And let me re-do it with an Opt-in.

**Comment by Clancey** [comment]
New pull request: https://github.com/praeclarum/sqlite-net/pull/505

**Pull request closed without merging**
